---
- hosts: all
  become: true
  pre_tasks:
#    - name: update ubuntu
#      tags: always
#      ansible.builtin.apt:
#        upgrade: dist
#        update_cache: yes
#      when: ansible_distribution == "Ubuntu"

    - name: update fedora
      tags: always
      ansible.builtin.dnf:
        name: '*'
        state: latest
      when: ansible_distribution == "Fedora"

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

#- hosts: fedora
#  become: true
# roles:
#   - fedora
